### PR TITLE
+ 🇷🇴 translation

### PR DESCRIPTION
**Pull request by irimia**
RO [SWAP](https://swap.solar.org/) translation

### CODE REVIEW

**Review by alessiodf — APPROVED** [review]

**Comment by alessiodf** [comment]
Hi @irimia!

Thanks for your pull request. I've approved the changes because you've implemented the translation properly in terms of the code changes required, but before merging I just wanted to ask you why some of the entries are either not translated at all or are half-English and half-Romanian?

Thanks!

**Comment by irimia** [comment]
To be honest I need to see it live so I can make some final touches or final translation (for the ones that aren't fully translated).

We use half English, half Romanian words (we call it `rom-english`) to express better something specific - some words are even introduced in our The Explanatory Dictionary of the Romanian Language.

**Comment by delkaos** [comment]
[here](https://docs.solar.org/sxpswap/users/metamask) you can find the screenshots of the whole procedure @irimia

**Comment by irimia** [comment]
Thanks. Should be OK now.

**Pull request merged**
